# Generated by Django 5.1.5 on 2025-01-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='ModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=20)),
                ('answer', models.TextField()),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_answers', to='answer.useranswer')),
            ],
            options={
                'db_table': 'model_answer',
            },
        ),
    ]
