# Generated by Django 5.1.5 on 2025-01-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelanswer',
            old_name='model_name',
            new_name='model_id',
        ),
    ]
