# Generated by Django 5.1.5 on 2025-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_useranswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanswer',
            name='model_id',
            field=models.CharField(max_length=50),
        ),
    ]
